---
title: "Human Genome Analysis"
output: html_document
date: 'Fall 2023'
---

This is a rendering of hmtl files from the course repository  (https://github.com/jeffreyblanchard/HumGen2023R) for Human Genome Analysis taught at the University of Massachusetts Amherst by Prof. Jeffrey Blanchard.  If you are not using RStudio (Posit) Cloud here are [directions](HumGen_github.html) for creating a RStudio project space that is in sync with the course github and will download the files in the course repo.

* Lab 1 : [Introduction to R and Reproducible Research](HumGen_Lab1_intro.html)
* Lab 2 : [Data Wrangling in the tidyverse](HumGen_Lab2_datawrangle.html)
* Lab 3 : [Introduction to ggplot2](HumGen_Lab3_datavis.html)
* Lab 4 : [More on ggplot2](HumGen_Lab4_pub_graphics.html)
* Lab 5 : [Human Genome Analysis Lab 5 : Linking 23andME SNPs to the NHGRI-EBI Catalog of published genome-wide association studies](HumGen_Lab5_gwcat.html)
* Lab 6 : [Human Genome Analysis Lab 6 : GWASCAT Part 2](HumGen_Lab6_gwascat.html)
